# Generated by Django 5.0.4 on 2024-04-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
